Garage3/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage3.Models
{
    public class Owner
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(128)]
        public string Name { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }

        public Owner()
        {
            Vehicles = new List<Vehicle>();
        }
    }
}

Garage3/Models/Parking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Garage3.Models
{
    public class Parking
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int ParkingSlotId { get; set; }

        [Required]
        public int VehicleId { get; set; }

        [Required]
        public DateTime DateIn { get; set; }

        public DateTime? DateOut { get; set; }

        [ForeignKey("VehicleId")]
        public virtual Vehicle Vehicle { get; set; }
    }
}

Garage3/Models/ParkingSlot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Garage3.Models
{
    public class ParkingSlot
    {
        [Key]
        public int Id { get; set; }

        public int? ParkingId { get; set; }

        [ForeignKey("ParkingId")]
        public virtual Parking Parking { get; set; }
    }
}

Garage3/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Garage3.Models
{
    public class Vehicle
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(32), Index(IsUnique=true)]
        public string RegNr { get; set; }

        [Required]
        public int OwnerId { get; set; }

        [Required]
        public int VehicleTypeId { get; set; }

        [ForeignKey("VehicleTypeId")]
        public virtual VehicleType Type { get; set; }

        [ForeignKey("OwnerId")]
        public virtual Owner Owner { get; set; }
    }
}

Garage3/Models/VehicleType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage3.Models
{
    public class VehicleType
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(64)]
        public string Name { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }

        public VehicleType()
        {
            Vehicles = new List<Vehicle>();
        }
    }
}

Garage3/Controllers/GarageController.cs
using Garage3.DataAccess;
using Garage3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage3.Controllers
{
    public class GarageController : Controller
    {
        private IGarageRepository repo;

        public GarageController()
        {
            repo = new GarageRepository(new GarageContext());
        }

        public GarageController(IGarageRepository repo)
        {
            this.repo = repo;
        }

        public ViewResult Index()
		{
			return View();
		}

		public ViewResult Manage()
		{
            ViewBag.Slots = repo.GetParkingSlots();
			return View();
		}

        public ViewResult History()
		{
			return View();
		}

        public ViewResult Api()
        {
            return View();
        }

		[HttpPost]
        public HttpStatusCodeResult Park(int slotId, string regNr, int? typeId, string ownerName)
		{
            var res = repo.Park(slotId, regNr, typeId, ownerName);
            switch (res)
            {
                case ParkResult.Success:
                    return new HttpStatusCodeResult(200);
                case ParkResult.AlreadyParked:
                    return new HttpStatusCodeResult(400, regNr + " is already parked");
                case ParkResult.NeedRegister:
                    return HttpNotFound("no vehicle with reg nr: " + regNr + " found");
            }
            return new HttpStatusCodeResult(500, "this can't ever happen");
		}

		// use a PUT method for unparking because all it involves
		// is updating ParkingSlots and Parkings with new values
		// (namely setting ParkingId to null in slots and setting DateOut in Parkings)
		[HttpPut]
		public HttpStatusCodeResult Unpark(int id)
		{
            var reg = repo.Unpark(id);
			return new HttpStatusCodeResult(200, "unparked " + reg);
		}

		// API: return an array of the slots in json format
        public JsonResult Slots()
        {
            var slots = repo.GetParkingSlots().Select(Selectors.ParkingSlotSelector);
            return Json(slots.ToList(), JsonRequestBehavior.AllowGet);
        }

		// API: return an array of parkings in json format
        public JsonResult Parkings(int? id)
        {
            var q = repo.GetParkings();
            if (id != null)
                q = q.Where(p => p.Id == id);
			var ps = q.Select(Selectors.ParkingSelector);
            return Json(ps.ToList(), JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            repo.Dispose();
            base.Dispose(disposing);
        }
    }
}

Garage3/Controllers/VehicleController.cs
using Garage3.DataAccess;
using Garage3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage3.Controllers
{
	// This is basically an API for angular to get data from

    public class VehicleController : Controller
    {
        private IGarageRepository repo;

        public VehicleController()
        {
            repo = new GarageRepository(new GarageContext());
        }

        public VehicleController(IGarageRepository repo)
        {
            this.repo = repo;
        }

		// return an array of vehicles, optionally filtered by id
        public JsonResult List(int? id)
        {
            var q = repo.GetVehicles();
            if (id != null)
                q = q.Where(v => v.Id == id);
            var vs = q.Select(Selectors.VehicleSelector);
            return Json(vs.ToList(), JsonRequestBehavior.AllowGet);
        }

		// return an array of owners, optionally filtered by id
        public JsonResult Owners(int? id)
        {
            var q = repo.GetOwners();
            if (id != null)
                q = q.Where(o => o.Id == id);
            var os = q.Select(Selectors.OwnerSelector);
            return Json(os.ToList(), JsonRequestBehavior.AllowGet);
        }

		// return an array of vehicle types, optionally filtered by id
		// can use this to populate drop down list
        public JsonResult Types(int? id)
        {
            var q = repo.GetVehicleTypes();
            if (id != null)
                q = q.Where(t => t.Id == id);
            var ts = q.Select(Selectors.VehicleTypeSelector);
            return Json(ts.ToList(), JsonRequestBehavior.AllowGet);
        }

		// Lookup a vehicle by RegNr
        public JsonResult ByRegNr(string id)
        {
            var vs = repo.FindVehicleByRegNr(id).Select(Selectors.VehicleSelector);
            return Json(vs.ToList(), JsonRequestBehavior.AllowGet);
        }

		// Get all vehicles with a specific type (by id)
        public JsonResult ByType(int id)
        {
            var vs = repo.GetVehiclesByType(id).Select(Selectors.VehicleSelector);
            return Json(vs.ToList(), JsonRequestBehavior.AllowGet);
        }

		// get all vehicles owner by ownerId
        public JsonResult ByOwner(int id)
        {
            var os = repo.GetVehiclesByOwner(id).Select(Selectors.VehicleSelector);
            return Json(os.ToList(), JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            repo.Dispose();
            base.Dispose(disposing);
        }
    }
}

Garage3/Views/Garage/Api.cshtml
@{
    ViewBag.Title = "Api";
}

<h2>Api</h2>

<div class="row" data-ng-app="api">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">Vehicles</h4>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="~/Vehicle/List">List</a> (id)</li>
                    <li><a href="~/Vehicle/ByRegNr">ByRegNr</a> (reg</li>
                    <li><a href="~/Vehicle/ByType/1">ByType</a> (id)</li>
                    <li><a href="~/Vehicle/ByOwner/1">ByOwner</a> (id)</li>
                    <li><a href="~/Vehicle/Types">Types</a> (id)</li>
                    <li><a href="~/Vehicle/Owners">Owners</a> (id)</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">Garage</h4>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="~/Garage/Slots">Slots</a> (id)</li>
                    <li><a href="~/Garage/Parkings">Parkings</a> (id)</li>
                </ul>
            </div>
        </div>
    </div>
</div>

Garage3/Views/Garage/History.cshtml
@{
    ViewBag.Title = "History";
}

@section scripts {
    <script src="~/App/history.js"></script>
}

<h2>History</h2>

<div class="row">
    <div data-ng-app="history" class="col-sm-12">
        <div data-ng-controller="historyCtrl">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title">Filtered display</h4>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-sm-4">
                            <div class="input-group">
                                <span class="input-group-addon widthFix">Reg nr</span>
                                <input data-ng-model="filterResults" class="form-control" type="search" placeholder="Type in registration number" />
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <span class="input-group-addon widthFix">Type</span>
                                <select class="form-control" name="typeId" data-ng-model="typeId">
                                    <option selected value="-1">Show All Types</option>
                                    <option data-ng-repeat="vt in vehicleTypes" value="{{ vt.id }}">{{ vt.name }}</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4 clear">
                            <div class="input-group">
                                <span class="input-group-addon widthFix">Owner</span>
                                <input data-ng-model="filterResultsOwn" class="form-control input-group" type="search" placeholder="Type in owner name" />
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div ng-show="showDurPri" class="input-group">
                                <span class="input-group-addon widthFix">Price</span>
                                <input data-ng-model="filterPrice" class="form-control" type="number" placeholder="Type in price per hour" />
                            </div>
                        </div>
                    </div>
                    <div class="clear">
                        <div class="col-sm-8">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="showTrueDur" ng-model="showTrueDur" />
                                    Show exact duration
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="showTrueDur" ng-model="showDurPri" />
                                    Show duration and price
                                </label>
                            </div>
                        </div>
                    </div>

                    <table class="table table-condensed">
                        <thead>
                            <tr>

                                <th class="HoverHand" ng-click="OrderBySID(sortID)">{{slot_id}}</th>
                                <th class="HoverHand" ng-click="OrderByDIn(sortID)">{{date_in}}</th>
                                <th class="HoverHand" ng-click="OrderByDOut(sortID)">{{date_out}}</th>
                                <th ng-show="showTrueDur">Exact duration</th>
                                <th ng-show="showDurPri" class="HoverHand" ng-click="OrderByDur(sortID)">{{duration}} (h)</th>
                                <th ng-show="showDurPri" class="HoverHand" ng-click="OrderByPrice(sortID)">{{sekprice}} SEK</th>
                                <th>Reg nr</th>
                                <th>Type</th>
                                <th>Owner</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr data-ng-repeat="p in parkings | filter:filterReg | filter:filterOwner | filter:typeFilterOn |orderBy:sortID">

                                <td>{{ p.slot_id }}</td>
                                <td>{{ p.date_in | date:'short' }}</td>
                                <td>{{ p.date_out | date:'short' }}</td>
                                <td ng-show="showTrueDur">{{p.trueDuration}}</td>
                                <td ng-show="showDurPri">{{ p.duration }}</td>
                                <td ng-show="showDurPri">{{ price(p) }}</td>
                                <td>{{ p.vehicle.reg}}</td>
                                <td>{{ p.vehicle.type.name }}</td>
                                <td>{{ p.vehicle.owner.name}}</td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Garage3/Views/Garage/Index.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="jumbotron">
    <ul id="bckgrdgraphline">
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
    </ul>
    <ul id="bckgrdgraphline">
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
    </ul>
    <ul id="bckgrdgraphline">
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
        <li><img src="~/Graphics/post-74607-0-43142200-1366894842.jpg" style="width:10%; height:10%;"></li>
    </ul>

    <h1>GARAGE 3.0</h1>

    <p class="lead">Taking care of your vehicles for a long long time.</p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Park your vehicle for limited amount of time or check out parked vehicles.
        </p>
        <p><a class="btn btn-default" href="~/Garage/Manage">Manage parking &raquo;</a></p>
    </div>
   
    <div class="col-md-4">
        <h2>Garage History</h2>
        <p>Here you can search and filter Vehicle database. Recommended for Admins only.</p>
        <p><a class="btn btn-default" href="~/Garage/History">Overview</a></p>
    </div>
</div>

Garage3/Views/Garage/Manage.cshtml
@model Garage3.Models.Vehicle

@{
    ViewBag.Title = "Manage";
}

@section scripts {
    <script src="~/App/manage.js"></script>
}
<h2>Manage</h2>

<div class="row">
    <div data-ng-app="manage" class="col-sm-12">
        <div data-ng-controller="manageCtrl">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title">Park &amp; Unpark vehicles</h4>
                </div>
                <div class="panel-body">
                    <div class="col-sm-12">
                        <button class="btn" style="width: 50px; margin: 1px" data-ng-repeat="s in slots | orderBy:'id'"
                                data-ng-class="[{'btn-default': !s.p_id, 'btn-warning': s.p_id}]"
                                data-ng-click="useSlot(s)"
                                data-toggle="modal" data-target="#box">
                            {{ s.id }}
                        </button>
                    </div>
                    <div id="box" class="modal fade" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                                    <h4>{{ headerText }}</h4>
                                    <div class="alert alert-{{ alertType }}" data-ng-show="alertMessage" style="margin-top: 10px">
                                        <strong>{{ alertMessage }}</strong>
                                    </div>
                                </div>

                                <div class="modal-body">

                                    <div data-ng-show="parking">
                                        <dl class="dl-horizontal">
                                            <dt>Slot:</dt>
                                            <dd>{{ parking.slot_id }}</dd>
                                            <dt>Reg nr:</dt>
                                            <dd>{{ parking.vehicle.reg }}</dd>
                                            <dt>Type:</dt>
                                            <dd>{{ parking.vehicle.type.name }}</dd>
                                            <dt>Owner:</dt>
                                            <dd>{{ parking.vehicle.owner.name }}</dd>
                                            <dt>Date in:</dt>
                                            <dd>{{ parking.date_in | date:'short'}}</dd>
                                            <dt>Parked for:</dt>
                                            <dd>{{ parking.date_dur }}</dd>
                                            <dd style="margin-top: 10px">
                                                <button class="btn btn-danger" type="button" data-ng-click="unpark()">Unpark</button>
                                            </dd>
                                        </dl>
                                    </div>

                                    <div data-ng-show="showRegForm">
                                        <form data-ng-submit="park()" class="form-horizontal">
                                            <div class="form-group">
                                                <label class="control-label col-sm-2" for="reg">Slot:</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="number" name="slotId" data-ng-model="slotId" />
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-2" for="reg">RegNr:</label>
                                                <div class="col-sm-10">
                                                    <input class="form-control" type="text" name="regNr" data-ng-model="regNr" />
                                                </div>
                                            </div>

                                            <div data-ng-show="showFullReg">
                                                <div class="form-group">
                                                    <label class="control-label col-sm-2" for="typeId">Type:</label>
                                                    <div class="col-sm-10">
                                                        <select class="form-control" name="typeId" data-ng-model="typeId">
                                                            <option data-ng-repeat="vt in vehicleTypes" value="{{ vt.id }}">{{ vt.name }}</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label col-sm-2" for="ownerName">Owner:</label>
                                                    <div class="col-sm-10">
                                                        <input class="form-control" type="text" name="ownerName" data-ng-model="ownerName" />
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                    <button class="btn btn-primary" type="submit">Park</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Garage3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Garage 3.0</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        body {
            background-color: #eee;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    <a href="~/Garage/Index"><img src="~/Content/logo.svg" width="24" height="24" />Garage 3.0</a>
                </div>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Manage", "Manage", "Garage")</li>
                    <li>@Html.ActionLink("History", "History", "Garage")</li>
                    <li>@Html.ActionLink("API", "Api", "Garage")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <footer class="navbar bottom ">
        <div class="container">
            <span class="navbar-brand"><small>&copy; @DateTime.Now.Year - Mårten, Nikola &amp; Martin</small></span>
        </div>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/i18n/angular-locale_sv-se.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script>
        window.garage = {}
        garage.rootPath = '@Url.Content("~")';
        garage.parseMSDate = function (s) {
            if (!s) return null;
            return new Date(parseInt(s.substr(6)));
        };
    </script>
    <script src="~/App/base.js"></script>
    @RenderSection("scripts", false)
</body>
</html>